{% set version = "0.3-8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rlecuyer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rlecuyer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rlecuyer/rlecuyer_{{ version }}.tar.gz
  sha256: 66bed3543337535fe2cf2d3eee4165472599c14d3c5e4402f7a1ebf5112c75c9

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('rlecuyer')"           # [not win]
    - "\"%R%\" -e \"library('rlecuyer')\""  # [win]

about:
  home: http://www.iro.umontreal.ca/~lecuyer/myftp/papers/streams00.pdf
  license: GPL-2.0-or-later
  summary: Provides an interface to the C implementation of the random number generator with multiple independent streams developed by L'Ecuyer et al (2002). The main purpose of this package is to enable the use of this random number generator in parallel R applications.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - FernandezMathieu

# Package: rlecuyer
# Version: 0.3-5
# Date: 2019-11-19
# Title: R Interface to RNG with Multiple Streams
# Authors@R: c( person("Hana", "Sevcikova", email="hanas@uw.edu", role=c("aut", "cre")), person("Tony", "Rossini", email="anthony.rossini@novartis.com", role="aut"), person("Pierre", "L'Ecuyer", role = "cph", comment="author of the underlying C code"))
# Description: Provides an interface to the C implementation of the random number generator with multiple independent streams developed by L'Ecuyer et al (2002). The main purpose of this package is to enable the use of this random number generator in parallel R applications.
# License: GPL (>= 2)
# URL: http://www.iro.umontreal.ca/~lecuyer/myftp/papers/streams00.pdf
# NeedsCompilation: yes
# Packaged: 2019-11-19 22:57:36 UTC; hana
# Author: Hana Sevcikova [aut, cre], Tony Rossini [aut], Pierre L'Ecuyer [cph] (author of the underlying C code)
# Maintainer: Hana Sevcikova <hanas@uw.edu>
# Repository: CRAN
# Date/Publication: 2019-11-21 22:40:02 UTC
